#pragma once

const char* WIFI_SSID = "YOUR_WIFI_SSID";
const char* WIFI_PASSWORD = "YOUR_WIFI_PASSWORD";
const char* SERVER_URL = "YOUR_HOSTING_SERVER_URL";
const char* DEVICE_SECRET = "YOUR_CUSTOM_DEVICE_SECRET";